name: shard-smp
version: '${version}'
main: me.lutto.shardsmp.ShardSMP
api-version: '1.20'
commands:
  giveitem:
    description: Give yourself a custom item!
    default: op
  resetcooldown:
    description: Reset item cooldowns!
    default: op
  upgradeItem:
    description: Upgrade upgradable weapons!
    default: op
  lives:
    description: Manage lives with this command!
    default: op
  donate:
    description: Donate your lives with this!
    default: op
  revive:
    description: Revive any player!
    default: op
  convertitem:
    description: Convert old custom item to new custom item!
    default: op
